name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: extension/ lemmy-keyboard-navigation.js lemmy-keyboard-navigation-mlmym.js
          dest: extension/dist.zip
